import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'CatJet',
  description: 'Generated by create next app',
};

/**
 * RootLayout component.
 *
 * @param {React.ReactNode} children - The children components.
 * @returns {React.ReactElement} The root layout component.
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
